development:
  adapter: mysql
  database: svid_development
  pool: 5
  username: dev_vid 
  password: snackfood
  socket: "/var/run/mysqld/mysqld.sock"

test:
  adapter: mysql
  database: svid_test
  pool: 5
  username: root 
  password: george
  socket: "/var/run/mysqld/mysqld.sock"

timeout: 5000

production:
  adapter: mysql
  database: sv_production
  pool: 5
  username: prod_vid 
  password: meat_and_potatoes
  socket: "/var/run/mysqld/mysqld.sock"

