development:
  adapter: mysql
  database: svid_development
  pool: 5
  username: dev_vid 
  password: snackfood
  socket: "/var/run/mysqld/mysqld.sock"

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: sv_production
  pool: 5
  username: prod_vid 
  password: meat_and_potatoes
  socket: "/var/run/mysqld/mysqld.sock"

